name: Workflow Actions

on:
  workflow_dispatch:
  push:
    branches: [main-modification]

jobs:
  build_gui:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Debug, Release]
        singlefile: [true, false]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3.5.2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: |
        dotnet build UndertaleModTool --no-restore
        dotnet build UndertaleModToolUpdater --no-restore
    
    - name: Publish ${{ matrix.os }} GUI
      run: |
        dotnet publish UndertaleModTool -c ${{ matrix.configuration }} -r win-x64 -p:PublishSingleFile=${{ matrix.singlefile }} --output ${{ matrix.os }}
        dotnet publish UndertaleModToolUpdater -c ${{ matrix.configuration }} -r win-x64 -p:PublishSingleFile=false --output ${{ matrix.os }}/Updater
    
    - name: Copy external files
      run: |
        cp ./README.md ./${{ matrix.os }}
        cp ./SCRIPTS.md ./${{ matrix.os }}
        cp ./LICENSE.txt ./${{ matrix.os }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
          name: GUI-${{ matrix.os }}-${{ matrix.configuration }}-isSingleFile-${{ matrix.singlefile }}
          path: GUI-${{ matrix.os }}-${{ matrix.configuration }}-isSingleFile-${{ matrix.singlefile }}.zip
